version: '2'

services:

  wordpress:
    container_name: wordpress
    image: wordpress:4.6.1-apache
    ports:
      - 2010:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    links:
      - mysql:mysql
    volumes:
      - ./wp-content:/var/www/html/wp-content
  mysql:
    container_name: database
    image: mariadb:10.1.19
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
